import { Injectable } from "@angular/core";

import { Item } from "./item";

@Injectable()
export class ItemService {
    private websites = [
        'facebook.com',
        'twitter.com',
        'google.com',
        'youtube.com',
        'instagram.com',
        'linkedin.com',
        'wordpress.org',
        'pinterest.com',
        'wikipedia.org',
        'wordpress.com',
        'blogspot.com',
        'apple.com',
        'adobe.com',
        'tumblr.com',
        'youtu.be',
        'amazon.com',
        'goo.gl',
        'vimeo.com',
        'flickr.com',
        'microsoft.com',
        'yahoo.com',
        'godaddy.com',
        'qq.com',
        'bit.ly',
        'vk.com',
        'reddit.com',
        'w3.org',
        'baidu.com',
        'nytimes.com',
        't.co',
        'europa.eu',
        'buydomains.com',
        'wp.com',
        'statcounter.com',
        'miitbeian.gov.cn',
        'jimdo.com',
        'blogger.com',
        'github.com',
        'weebly.com',
        'soundcloud.com',
        'mozilla.org',
        'bbc.co.uk',
        'yandex.ru',
        'myspace.com',
        'google.de',
        'addthis.com',
        'nih.gov',
        'theguardian.com',
        'google.co.jp',
        'cnn.com',
        'stumbleupon.com',
        'gravatar.com',
        'digg.com',
        'addtoany.com',
        'creativecommons.org',
        'paypal.com',
        'yelp.com',
        'imdb.com',
        'huffingtonpost.com',
        'feedburner.com',
        'issuu.com',
        'wixsite.com',
        'wix.com',
        'dropbox.com',
        'forbes.com',
        'miibeian.gov.cn',
        'amazonaws.com',
        'google.co.uk',
        'washingtonpost.com',
        'bluehost.com',
        'etsy.com',
        'go.com',
        'msn.com',
        'wsj.com',
        'ameblo.jp',
        'archive.org',
        'slideshare.net',
        'e-recht24.de',
        'weibo.com',
        'fc2.com',
        'eventbrite.com',
        'parallels.com',
        'doubleclick.net',
        'mail.ru',
        'sourceforge.net',
        'amazon.co.uk',
        'telegraph.co.uk',
        'ebay.com',
        'amzn.to',
        'livejournal.com',
        '51.la',
        'free.fr',
        'yahoo.co.jp',
        'dailymail.co.uk',
        'reuters.com',
        'taobao.com',
        'wikimedia.org',
        'amazon.de',
        'typepad.com',
        'hatena.ne.jp',
        'bloomberg.com',
    ];

    private items: Item[] = this.websites.map((w, index) => {
        return { id: index + 1, name: w, role: "https://" + w };
    });

    getItems(): Item[] {
        return this.items;
    }

    getItem(id: number): Item {
        return this.items.filter(item => item.id === id)[0];
    }
}
